name: morning class 1st workflow
on:
  push:
    branches:
      - main
      - 'features/**'
jobs:
  my_first_job:
      name: morning first job
      runs-on: self-hosted
      steps:
        - name: Hare Krishna
          env:
            MY_VAR: Hi there!! we are DevOps team!!!
            MESSAGE: we are devoteee of Shree Krishna
            run: |
              "echo $env:MY_VAR $env:MESSAGE"
